package constants

const (
	SERVER_PORT = "SERVER_PORT"

	NATS_URL       = "NATS_URL"
	CLUSTER_ID     = "CLUSTER_ID"
	NATS_CLIENT_ID = "NATS_CLIENT_ID"

	POSTGRES_HOST     = "POSTGRES_HOST"
	POSTGRES_PORT     = "POSTGRES_PORT"
	POSTGRES_USER     = "POSTGRES_USER"
	POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
	POSTGRES_DB       = "POSTGRES_DB"
	POSTGRES_SSL      = "POSTGRES_SSL"
)
